---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: busser

platforms:
  - name: ubuntu-14.04
  - name: centos-6.8
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[spartan_loggly_rsyslog::default]
    attributes:
      loggly:
        token: test_token
        tags:
          - Vagrant
          - test
        log_files:
          - filename: /tmp/test.log
        apps:
          nginx:
            - filename: /tmp/nginx-access.log
              tag: custom-nginx-access
              statefile: /tmp/custom-nginx-state-file
            - filename: /tmp/nginx-ssl-access.log
              tag: custom-nginx-access
            - filename: /tmp/nginx-error.log
