require 'serverspec'

set :backend, :exec

describe service('rsyslog') do
  it { should be_enabled }
  it { should be_running }
end

describe file('/etc/rsyslog.d/22-loggly.conf') do
  it { should be_file }

  [
    '$DefaultNetstreamDriverCAFile /etc/rsyslog.d/keys/ca.d/logs-01.loggly.com_sha12.crt',
    '$ActionSendStreamDriver gtls',
    '$ActionSendStreamDriverMode 1',
    '$ActionSendStreamDriverAuthMode x509/name',
    '$ActionSendStreamDriverPermittedPeer *.loggly.com',
    '[test_token@41058 tag=\\"Vagrant\\" tag=\\"test\\"]',
    'target="logs-01.loggly.com" port="6514"'
  ].each do |line|
    its(:content) { should match(/#{Regexp.escape(line)}/) }
  end
end

describe file('/etc/rsyslog.d/99-files.conf') do
  it { should be_file }

  expected_files_conf = <<-EOS.gsub(/^    /, '')
    # This file was generated by Chef

    module(load="imfile" PollingInterval="10")

    input(type="imfile"
          File="/tmp/test.log"
          Tag="test-log"
          Statefile="/tmp/test.log.rsyslog_state"
      )
  EOS

  its(:content) { should eq expected_files_conf }
end
